require: rubocop-rails
Metrics/LineLength:
  Max: 100
Style/FrozenStringLiteralComment:
  Enabled: false
Rails:
  Enabled: true
Metrics/BlockLength:
  Exclude:
    - 'test/**/*.rb'
AllCops:
  Exclude:
    - 'test/dummy/**/*'
    - 'bin/*'
Style/TrivialAccessors:
  IgnoreClassMethods: true
