plugins:
  - rubocop-rails

AllCops:
  NewCops: enable
  Exclude:
    - "test/dummy/**/*"
    - "bin/*"

# https://docs.rubocop.org/rubocop/cops_gemspec.html#enforcedstyle_-forbidden-gemspecdependencyversion
# Enforce that gem dependency version specifications or a commit reference
# (branch, ref, or tag) are either required or forbidden.
Gemspec/DependencyVersion:
  EnforcedStyle: forbidden

Layout/LineLength:
  Max: 100
  AllowedPatterns: ['^(\s*#)']
  Exclude:
    - qonsole_rails.gemspec
    - "test/**/*"

Metrics/AbcSize:
  Max: 30
  Exclude:
    - qonsole_rails.gemspec
    - test/**/*
Metrics/BlockLength:
  Max: 30
  Exclude:
    - qonsole_rails.gemspec
    - "test/**/*"

Metrics/ClassLength:
  CountAsOne: ["array", "hash", "heredoc", "method_call"]
  Exclude:
    - test/**/*

Metrics/MethodLength:
  CountAsOne: ["array", "hash", "heredoc", "method_call"]
  Exclude:
    - test/**/*
    - lib/tasks/**/*

Rails:
  Enabled: true

Style/FormatStringToken:
  Enabled: false

Style/OptionalBooleanParameter:
  Enabled: false
    
Style/ClassAndModuleChildren:
  Exclude:
    - test/**/*
    
Style/Documentation:
  Exclude:
    - "test/**/*"

Style/FrozenStringLiteralComment:
  Enabled: false

Style/TrivialAccessors:
  IgnoreClassMethods: true
